// <auto-generated />
namespace KL_E_Commerce.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editedProducts3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedProducts3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210616258_editedProducts3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
