// <auto-generated />
namespace KL_E_Commerce.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editedStockProductsManufacturer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedStockProductsManufacturer));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210756322_editedStockProductsManufacturer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
