// <auto-generated />
namespace KL_E_Commerce.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class categoryEdit1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryEdit1));
        
        string IMigrationMetadata.Id
        {
            get { return "201806200713246_categoryEdit1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
